version: '3'

services:
  part5:
    build:
      context: .
      dockerfile: Dockerfile-part5
    container_name: fastcgi_nginx
  nginx-proxy:
    image: nginx
    container_name: fastcgi_nginx_proxy
    ports:
      - 80:8080
    volumes:
      - ./part_6/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - part5
